### PR TITLE
command pg build-settings-type added

### PR DESCRIPTION
**Pull request by yuki-tylar**

### CODE REVIEW

File: packages/@pinglue/mongodb-pl/src/settings.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
+/* tslint:disable */
```
Comment (pmvald) [inline packages/@pinglue/mongodb-pl/src/settings.ts:1]: this should be moved to the test file. We also need to removed all these comments.  

In general we should not modify any package other than the one we are working on. All these testing should be done with the fake fs as explained in my last post.

File: packages/@pinglue/cli/src/actions/build-settings-type.ts [hunk 2]
```diff
@@ -0,0 +1,74 @@
+import { CliActionSettings } from "cli-settings";
+import { Options } from "yaml";
+import fs from 'fs-extra';
+import path from 'path';
+import yaml from 'yaml';
+import jsonToTypeScript from 'json-schema-to-typescript';
+import { print, style } from "@pinglue/print/node";
```
Comment (pmvald) [inline packages/@pinglue/cli/src/actions/build-settings-type.ts:7]: these two should come from the settings. Please check other action files.

File: packages/@pinglue/cli/src/actions/build-settings-type.ts [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+
+export default function (settings: CliActionSettings) {
+  return async (routeName: string, options: Options) => {
+    routeName = routeName || '/';
+
+    // Find registers.yaml file and read
+    print('Loading pg.yaml file...\n');
+
+    const filepath = path.join('pg.yaml');
```
Comment (pmvald) [inline packages/@pinglue/cli/src/actions/build-settings-type.ts:16]: path.join is needed when you have more than one parts. right now `path.join('abs') === 'abc'`

File: packages/@pinglue/cli/src/actions/build-settings-type.ts [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+import { Options } from "yaml";
+import fs from 'fs-extra';
+import path from 'path';
+import yaml from 'yaml';
+import jsonToTypeScript from 'json-schema-to-typescript';
+import { print, style } from "@pinglue/print/node";
+
+export default function (settings: CliActionSettings) {
+  return async (routeName: string, options: Options) => {
+    routeName = routeName || '/';
```
Comment (pmvald) [inline packages/@pinglue/cli/src/actions/build-settings-type.ts:11]: `./`

File: packages/@pinglue/cli/src/actions/build-settings-type.ts [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+    if(!promise) {
+      print.error('Could not find settings definition in pg.yaml. To generate setting type, please set settings section in pg.yaml');
+      return;
+    }
+
+    let settingsType: String;
+    try {
+      settingsType = await promise;      
+    } catch (error) {
+      print.error('Could not compile settings data into typescript format properly. It may be caused because pg.yaml has incorrect format\n');
```
Comment (pmvald) [inline packages/@pinglue/cli/src/actions/build-settings-type.ts:53]: `print.error(message, data)`  -> data will be automatically printed with `errorObj` style

File: packages/@pinglue/cli/src/actions/build-settings-type.ts [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+      print('Here is more information.');
+      print(style.errorObj(error));
+      return;
+    }
+
+    print.success('Compile done. exporting...\n');
+
+    const dirToWrite = path.join('./src');
```
Comment (pmvald) [inline packages/@pinglue/cli/src/actions/build-settings-type.ts:61]: not needed

**Review by pmvald — CHANGES_REQUESTED** [review]
Now you can add a few tests following `build-channels-types.spec.ts`

**Comment by yuki-tylar** [comment]
updated as you mentioned.
I also modified build-settings-types because these two files have some same mistake.

**Comment by pmvald** [comment]
Some parts seem to be the old code. Right now your branch is three commits behind the main. So first do a sync with the main. I think some new changes in main must have affected your work as well. As a general rule, always watch for new commits in main and sync to them to avoid conflict and building on old code.

**Comment by yuki-tylar** [comment]
I merged `main` into the branch and I tried `5pm run build-ts` in `cli` folder to check if it works properly. but the command `build-ts` got errors such as `Module '"@pinglue/utils/testing/replace-module"' has no exported member 'resetModules'.`

These are related to testing-unit, so I thought I might miss some dependencies. (maybe Jasmine / Mocha or something)

So, I tried these commands at root
```
npm install <-- ok
npm run bt <-- NG (see ERROR1 below)
npm run bt --force <-- ok
npm run build-ts <-- NG (see ERROR2 below)
```

And went back to `cli` folder and did `npm run build-ts`. I still got same error.
Am I still missing something to compile with testing unit properly?


here is ERROR1
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: pg-monorepo@undefined
npm ERR! Found: typescript@4.5.5
npm ERR! node_modules/typescript
npm ERR!   typescript@"4.5.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"4.0.x || 4.1.x || 4.2.x || 4.3.x || 4.4.x" from typedoc@0.21.10
npm ERR! node_modules/typedoc
npm ERR!   typedoc@"^0.21.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

here is ERROR2
```
src/testing/fake-fs.ts(4,13): error TS2339: Property 'native' does not exist on type '{ (path: PathLike, callback: TCallback<TDataOut>): any; (path: PathLike, options: string | IRealpathOptions, callback: TCallback<...>): any; }'.
@pinglue/utils: src/testing/fake-fs.ts(5,4): error TS2339: Property '__fake' does not exist on type 'IFs'.
```

**Comment by pmvald** [comment]
right now this branch has only two commits. Maybe you did the merge on your local computer. So you can push the commit here and we'll look into it. This must be a basic problem for sure.

**Comment by yuki-tylar** [comment]
I pushed the new branch in which main is merged.

**Comment by pmvald** [comment]
Just by looking at the page I can see that the problem is the merge was done properly. You see it says there is conflict
Screenshot
:
Now I'll try to find more details. But in general you can refer to the guides I posted here and there. There must be some guide for merging and resolving conflicts. We all need to know how to sync branches with main, this is a common thing we do all the time.

**Comment by pmvald** [comment]
Error 2 is easy, we just need to make the extra fields as indices. I just did it now at [this commit](https://github.com/pinglue/pg-repo/commit/911efa0f0c2a1033b683154f97ab180fe4c7442f) - you can do another sync

**Comment by pmvald** [comment]
For Error 1, our version of typedoc package is old and it does not work with typescript 4.5.5 - but the new version of typedoc (0.22.12) works with 4.5.x as well, [see here](https://github.com/TypeStrong/typedoc/blob/master/package.json) - so you can star ta new branch and update typedoc version to 0.22.12 for all the packages in pg-repo - using lerna from monorepo root:

```
lerna add typedoc@0.22.12 --scope=pinglue --scope=@pinglue/*
```
Then make a PR!

**Comment by yuki-tylar** [comment]
I finally did run properly. Thank you!
I made some small changes at `build-channels.types.ts`.

**Comment by yuki-tylar** [comment]
Removed following types files in mongodb-pl
* settings.ts
* channels-types.ts 
* route1/channels-types.ts

Removed unnecessary `promise` check

**Review by pmvald — COMMENTED** [review]
test file? (build-settings-type.spec.ts)

**Comment by yuki-tylar** [comment]
* Added spec file (I don't know why but I could not create fake `src/settings.ts` file by running the command, so I added the fake empty `src/settings.ts` file manually in fake volume.
* removed comment `generated by Pinglue Cli automatically`. from build-settings-type and build-channels-types

File: packages/@pinglue/cli/src/actions/build-settings-type.spec.ts [hunk 7]
```diff
@@ -0,0 +1,161 @@
...
+
+    // see the file system
+    // console.log(fakeVolume.toJSON());
+
+    // last message was a success
+    expect(fakeConsole.last().type).to.equal("success");
+
+    const regex = new RegExp(/\s+/g);
+    let returnValue = fakeFs.readFileSync("src/settings.ts", "utf8").toString().trim().replace(regex, ' ');
+    let expectedValue = SETTINGS_TYPE.trim().replace(regex, ' ');
```
Comment (pmvald) [inline packages/@pinglue/cli/src/actions/build-settings-type.spec.ts:137]: Modifying expected and return values in this way is potentially dangerous. You want to see if two codes are equal ignoring indentations? This is a complicated task to do. So lets do it easy way: compare the return value with what it should "exactly" be (including all the white spaces/indentations) 

we also usually hardcode the expected value for each test. So the variable SETTINGS_TYPE is better to define within this test instead of being global (each test will have different values for these variables)

**Review by pmvald — CHANGES_REQUESTED** [review]

**Review by pmvald — APPROVED** [review]
